spring:
  application:
    name: spring-react-studentdatabase
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: true
    # show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl.auto: update
      format_sql: true
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl