spring:
  main:
    allow-circular-references: true
  application:
    name: database-javaspring-reactjs
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    # show-sql: true
    generate-ddl: true
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      # ddl.auto: "update" 
      # will add new columns & constraints
      # but will never remove columns & constaints that no longer exists
      ddl.auto: create
      format_sql: true
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      session.events.log.LOG_QUERIES_SLOWER_THAN_MS: 1 # 20
